# Generated by Django 5.0.2 on 2025-03-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='password',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='curp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='matricula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='rfc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
