# Generated by Django 5.0.2 on 2025-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0004_remove_alumnos_email_remove_alumnos_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('publico_objetivo', models.TextField()),
                ('programa', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cupo', models.IntegerField()),
            ],
        ),
    ]
