# Generated by Django 5.0.2 on 2025-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0005_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
