# Generated by Django 5.0.2 on 2025-05-22 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0007_alter_administradores_options_alter_alumnos_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administradores',
            options={},
        ),
        migrations.AlterModelOptions(
            name='alumnos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maestros',
            options={},
        ),
        migrations.AlterField(
            model_name='administradores',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='lugar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='programa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='publico_objetivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='responsable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='administradores',
            table=None,
        ),
        migrations.AlterModelTable(
            name='alumnos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='eventos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='maestros',
            table=None,
        ),
    ]
