# Generated by Django 5.0.2 on 2025-05-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0008_alter_administradores_options_alter_alumnos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administradores',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='alumnos',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='maestros',
            options={'verbose_name': 'Maestro', 'verbose_name_plural': 'Maestros'},
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='publico_objetivo',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='administradores',
            table='administradores',
        ),
        migrations.AlterModelTable(
            name='alumnos',
            table='alumnos',
        ),
        migrations.AlterModelTable(
            name='eventos',
            table='eventos',
        ),
        migrations.AlterModelTable(
            name='maestros',
            table='maestros',
        ),
    ]
