# Generated by Django 5.0.2 on 2025-05-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0009_alter_administradores_options_alter_alumnos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administradores',
            options={},
        ),
        migrations.AlterModelOptions(
            name='alumnos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maestros',
            options={},
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='publico_objetivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='administradores',
            table=None,
        ),
        migrations.AlterModelTable(
            name='alumnos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='eventos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='maestros',
            table=None,
        ),
    ]
